
export const dataFood = [
    {
        id:"e8efc6f893c2452fb08fd8e539c0b7f2",
        productName:"BigMac",
        isToyAvailable: false,
        description:"a perfección hecha hamburguesa que te hace agua la boca comienza con dos patties de 100% carne y la salsa Big Mac®, todo dentro de un pan con semillas de ajonjolí. Viene cubierta con pepinillos, crujiente lechuga, cebollas y queso americano para lograr ese sabor único de la hamburguesa 100% de carne.",
        ingredients:["pan","tomate","cebolla","mayonesa","carneSorpresa"],
        price: 7.99,
        score:3.5,
        img: "https://mcdonalds.es/api/cms/images/mcdonalds-es/Zgu-4ct2UUcvBUuX_2500x2500_BigMac.png?auto=format,compress",
    },
    {
        id:"102a1b5dbe3e44179b1bb30534374228",
        productName:"pollo",
        isToyAvailable:false,
        description:"lorem",
        ingredients: ["alas", "muslos", "pechuga"],
        price: 5,
        score: 4,
        img: "https://okdiario.com/img/2022/01/30/pollo-frito-3-655x368.jpg",
    },
    {
        id:"8d04c6423d164f7d8e1b5b14f39ea3df",
        productName:"pizza",
        isToyAvailable:false,
        description:"lorem pizza",
        ingredients:["tomate, peperoni, queso"],
        price: 8,
        score: 3,
        img:"https://www.just-eat.es/CmsAssets/media/Images/Chains/Dominos-Pizza/Editorial-533x300.jpg?bid=c0fb6c1b6eba46d79d6a79fed0efb7cb",
    },
    {
        id:"2a876f44f33d4ee8aea24e0c8c3768cd",
        productName:"ensalada",
        isToyAvailable:true,
        description:"lorem ensalada",
        ingredients:["lechuga", "tomate", "pepino", "cebolla"],
        price:4,
        score:3,
        img:"https://d36fw6y2wq3bat.cloudfront.net/recipes/ensalada-cremosa-rapidisima/900/ensalada-cremosa-rapidisima_version_1646280172.jpg",
    },
    {
        id:"76667cbe4afc4f0e8466f35c31d22850",
        productName:"burrito",
        isToyAvailable: false,
        description:"burrito burron",
        ingredients: ["pollo", "carne", "maiz"],
        price: 6,
        score:5,
        img:"https://i.ytimg.com/vi/krkf7ObsTM4/maxresdefault.jpg",
    },
    {
        id:"2059fdd0b9f540a2a2feb87cdb7af5c4",
        productName:"cachapa",
        isToyAvailable:false,
        description:"cachapa rica",
        ingredients:["maiz", "queso"],
        price: 6,
        score: 5,
        img:"https://miro.medium.com/v2/resize:fit:1024/1*3P4GSfdcNs7dPyEscIt4oQ.jpeg",
    },
    {
        id:"e951581033e94e2989a9945d8cd8a032",
        productName:"pasta",
        isToyAvailable: true,
        description:"pasata de camarones",
        ingredients: ["pasta", "camarones"],
        price: 9,
        score: 5,
        img:"https://www.gastrolabweb.com/u/fotografias/m/2023/12/13/f608x342-55597_85320_5136.jpg",
    },
    {
        id:"6c25d85fef9343d38769199507fdc4a1",
        productName:"empanada argentina",
        isToyAvailable: false,
        description:"empanada de carne",
        ingredients: ["carne", "pollo", "maiz"],
        price: 2,
        score: 4,
        img:"https://www.divinacocina.es/wp-content/uploads/2021/10/empanadas-criollas-C.jpg",
    },
    {
        id:"58b8a2fd15c3446aa7f3d5acce03e168",
        productName:"pollo rostizado",
        isToyAvailable:"true",
        description:"pollo al carbon",
        ingredients: ["pollo", "yuca", "ensalada"],
        price: 10,
        score: 5,
        img:"https://hosdecora.com/blog/wp-content/uploads/2017/10/Pollo-asado.png",
    },
];